//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = true)]
/*[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.microsoft.com/VSET/TeamBuilds/2004/08/mtservices/buildCompletionEv" +
    "ent")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.microsoft.com/VSET/TeamBuilds/2004/08/mtservices/buildCompletionEv" +
    "ent", IsNullable=false)]*/
public partial class BuildCompletionEvent2 {
    
    private string teamFoundationServerUrlField;
    
    private string urlField;
    
    private string teamProjectField;
    
    private string agentPathField;
    
    private string definitionPathField;
    
    private string buildNumberField;
    
    private string startTimeField;
    
    private string finishTimeField;
    
    private string configurationFolderUriField;
    
    private string sourceGetVersionField;
    
    private string qualityField;
    
    private string statusField;
    
    private string statusCodeField;
    
    private string compilationStatusField;
    
    private string testStatusField;
    
    private string logLocationField;
    
    private string dropLocationField;
    
    private string requestedForField;
    
    private string requestedByField;
    
    private string lastChangedOnField;
    
    private string lastChangedByField;
    
    private bool keepForeverField;
    
    private string timeZoneField;
    
    private string timeZoneOffsetField;
    
    private string subscriberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string TeamFoundationServerUrl {
        get {
            return this.teamFoundationServerUrlField;
        }
        set {
            this.teamFoundationServerUrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string Url {
        get {
            return this.urlField;
        }
        set {
            this.urlField = value;
        }
    }
    
    /// <remarks/>
    public string TeamProject {
        get {
            return this.teamProjectField;
        }
        set {
            this.teamProjectField = value;
        }
    }
    
    /// <remarks/>
    public string AgentPath {
        get {
            return this.agentPathField;
        }
        set {
            this.agentPathField = value;
        }
    }
    
    /// <remarks/>
    public string DefinitionPath {
        get {
            return this.definitionPathField;
        }
        set {
            this.definitionPathField = value;
        }
    }
    
    /// <remarks/>
    public string BuildNumber {
        get {
            return this.buildNumberField;
        }
        set {
            this.buildNumberField = value;
        }
    }
    
    /// <remarks/>
    public string StartTime {
        get {
            return this.startTimeField;
        }
        set {
            this.startTimeField = value;
        }
    }
    
    /// <remarks/>
    public string FinishTime {
        get {
            return this.finishTimeField;
        }
        set {
            this.finishTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI")]
    public string ConfigurationFolderUri {
        get {
            return this.configurationFolderUriField;
        }
        set {
            this.configurationFolderUriField = value;
        }
    }
    
    /// <remarks/>
    public string SourceGetVersion {
        get {
            return this.sourceGetVersionField;
        }
        set {
            this.sourceGetVersionField = value;
        }
    }
    
    /// <remarks/>
    public string Quality {
        get {
            return this.qualityField;
        }
        set {
            this.qualityField = value;
        }
    }
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CompilationStatus {
        get {
            return this.compilationStatusField;
        }
        set {
            this.compilationStatusField = value;
        }
    }
    
    /// <remarks/>
    public string TestStatus {
        get {
            return this.testStatusField;
        }
        set {
            this.testStatusField = value;
        }
    }
    
    /// <remarks/>
    public string LogLocation {
        get {
            return this.logLocationField;
        }
        set {
            this.logLocationField = value;
        }
    }
    
    /// <remarks/>
    public string DropLocation {
        get {
            return this.dropLocationField;
        }
        set {
            this.dropLocationField = value;
        }
    }
    
    /// <remarks/>
    public string RequestedFor {
        get {
            return this.requestedForField;
        }
        set {
            this.requestedForField = value;
        }
    }
    
    /// <remarks/>
    public string RequestedBy {
        get {
            return this.requestedByField;
        }
        set {
            this.requestedByField = value;
        }
    }
    
    /// <remarks/>
    public string LastChangedOn {
        get {
            return this.lastChangedOnField;
        }
        set {
            this.lastChangedOnField = value;
        }
    }
    
    /// <remarks/>
    public string LastChangedBy {
        get {
            return this.lastChangedByField;
        }
        set {
            this.lastChangedByField = value;
        }
    }
    
    /// <remarks/>
    public bool KeepForever {
        get {
            return this.keepForeverField;
        }
        set {
            this.keepForeverField = value;
        }
    }
    
    /// <remarks/>
    public string TimeZone {
        get {
            return this.timeZoneField;
        }
        set {
            this.timeZoneField = value;
        }
    }
    
    /// <remarks/>
    public string TimeZoneOffset {
        get {
            return this.timeZoneOffsetField;
        }
        set {
            this.timeZoneOffsetField = value;
        }
    }
    
    /// <remarks/>
    public string Subscriber {
        get {
            return this.subscriberField;
        }
        set {
            this.subscriberField = value;
        }
    }
}
